### ISSUE TITLE
Moisture Content Cones - Activity results table part 2

### ISSUE THREAD

**Issue by SLDonnelly** [bcgov/nr-spar#1785]
**As a** *TSC User* **I want** *previously entered data to appear in the activity results table feature* **So That** *I can view, edit or delete previous entered data*

**Acceptance Criteria**
- [ ] Given that data was previous entered, when I open the screen, all the fields in the activity results table retrieve the data that was entered. #1787
- [ ] Given that the activity has not been accepted, when I click on the add row button, a new row with the next replicate number is added to the bottom of the table. 
- [ ] Given that the activity has not been accepted, when I update data in a field, the changes are saved.
- [ ] Given I am on the Moisture Content screen, when I enter data into the table, then it gets saved as I am entering data.
- [ ] Given that I have the correct permission, when I **update** data into the activity results per replicate table, data is **updated** in the corresponding fields that have been mapped out #1786 
- [ ] Given that I have the correct permission, when I **delete** data in the activity results per replicate table, data is **deleted** in the corresponding fields that have been mapped out #1788

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/sdonnell/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/sdonnell/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

</head>

<body link="#467886" vlink="#96607D">

Screen Name | Record Source | Old Form Field | New Form Field | Table | Column | Type
-- | -- | -- | -- | -- | -- | --
Moisture Content Cones | qryCNSL25_MC | Override Reason | TBD | CNS_T_TEST_REP_MC | TOLRNC_OVRRDE_DESC | VARCHAR2(2000)
Moisture Content Cones | qryCNSL25_MC | Replicate | Replicate | CNS_T_TEST_REP_MC | TEST_REPLICATE_NO | Number (5,0)
Moisture Content Cones | qryCNSL25_MC | Rep Comment | Comments | CNS_T_TEST_REP_MC | REPLICATE_COMMENT | VARCHAR2(255)
Moisture Content Cones | qryCNSL25_MC | Accept? | Acc | CNS_T_TEST_REP_MC | REP_ACCEPTED_IND | Number (5,0)
Moisture Content Cones | qryCNSL25_MC | Fresh Seed Only | Fresh seed | CNS_T_TEST_REP_MC | FRESH_WEIGHT | Number (7,3)
Moisture Content Cones | qryCNSL25_MC | Dry Weight | Dry weight | CNS_T_TEST_REP_MC | DRY_WEIGHT | Number (7,3)
Moisture Content Cones | qryCNSL25_MC | Container Weight | Container weight | CNS_T_TEST_REP_MC | CONTAINER_WEIGHT | Number (7,3)
Moisture Content Cones | qryCNSL25_MC | Container Number | Container # | CNS_T_TEST_REP_MC | CONTAINER_ID | Varchar2(4)
Moisture Content Cones | qryCNSL25_MC | Cont + Dry Seed | Cont + Dry seed | CNS_T_TEST_REP_MC | CNTNR_AND_DRY_WGHT | Number (7,3)

</body>

</html>

**Additional Context**
Mapped Endpoints: https://bcgov-my.sharepoint.com/:x:/r/personal/sabina_donnelly_gov_bc_ca/Documents/!%20SPAR%20Modernization/CONSEP_Screen_Documentation/[CONSEP_Screen_fields.xlsx](https://bcgov-my.sharepoint.com/:x:/r/personal/sabina_donnelly_gov_bc_ca/Documents/!%20SPAR%20Modernization/CONSEP_Screen_Documentation/CONSEP_Screen_fields.xlsx?d=wd074157a0e5046f894d8a303a5b47225&csf=1&web=1&e=HRWZ83)?d=wd074157a0e5046f894d8a303a5b47225&csf=1&web=1&e=HRWZ83

Figma design for Moisture Content Cones: https://www.figma.com/design/wWqNmvDMzrJDU8NDpCJ46b/Testing-activities-(Purity---Moisture---Xray---Fungal---SPG---etc.)?node-id=2249-59413&t=CVqpWRq9R4n6MeVq-4

**Definition of Done**
- [ ] Ready to Demo in Sprint Review
- [ ] Does what I have made have appropriate test coverage?
- [ ] Documentation and/or scientific documentation exists and can be found
- [ ] Peer Reviewed by 2 people on the team
- [ ] Manual testing of all PRs in Dev and Prod
- [ ] QA from UX team member
- [ ] Merged
